apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: alumni-shared-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
    # tls:
    #   httpsRedirect: true  <-- REMOVE OR COMMENT OUT THIS LINE
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: alumni-tls 
    hosts:
    - "*"