apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-email-worker
  labels:
    app: notification-email-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-email-worker
  template:
    metadata:
      labels:
        app: notification-email-worker
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: email-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "workers/emailWorker.js"]
          env:
            # --- Dynamic Cluster Routing URL ---
            - name: KAFKA_BROKER
              value: "kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
              
            # --- Secrets Configuration ---
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.secretName }}
                  key: RESEND_API_KEY
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi