apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-incident-worker
  labels:
    app: notification-incident-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-incident-worker
  template:
    metadata:
      labels:
        app: notification-incident-worker
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: incident-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "workers/incidentWorker.js"]
          #ADDED TO LOAD THE SECRETS
          envFrom:
            - secretRef:
                name: {{ .Values.env.secretName }}

          env:
            # --- Dynamic Cluster Routing URL ---
            - name: KAFKA_BROKER
              value: "kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi