image:
  repository: ""
  pullPolicy: Always
  tag: ""
  
imagePullSecrets:
  - name: nexus-creds
  
service:
  port: 3000
  targetPort: 3000

env:
  # kafkaBrokers: "alumni-kafka:9092"
  KAFKA_BROKER: "kafka:9092"
  secretName: "alumni-secrets"
