apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kanishkpandey18/git-infra-repo.git'
    targetRevision: main
    path: charts/velero-agent
    helm:
      valueFiles:
        - ../../argocd/prod/values/velero-prod.yaml
  destination:
    name: prod-cluster
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
