image:
  repository: "192.168.41.90:8082/alumni-notification"
  tag: "v2"
  
env:
  # Strictly isolated to the Prod cluster namespace (or just "kafka:9092" if relying on local namespace resolution)
  KAFKA_BROKER: "kafka.alumni-portal-prod.svc.cluster.local:9092"
