apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alumni-routing-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kanishkpandey18/git-infra-repo.git'
    targetRevision: main
    path: charts/shared-istio-routing
    helm:
      parameters:
        - name: wafEnabled
          value: "true"
        - name: cloudflareToken
          value: "eyJhIjoiMjdkNTdhZDZhMDY1NGFlNTQzNjY0Nzc0Mjg5YzJmN2IiLCJ0IjoiMTE4ZmJkMDYtZDhmMy00OWUxLThkNjMtNTMwNDZlMzI0MzBjIiwicyI6Ik5qUm1aV1ZqTlRZdE9XVTNNUzAwT0RreUxUZzJaVGN0WmpWak5ERmtORGRqWlRnMSJ9"
  destination:
    name: dev-cluster
    namespace: alumni-portal-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true